### ISSUE TITLE
Requires latest libstdcxx-ng

### ISSUE THREAD

**Issue by QuLogic** [conda-forge/contourpy-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In my existing matplotlib environment, I installed contourpy from conda-forge, but it failed to import due to missing C++ symbols. In a clean environment, it works fine, but I can replicate the failure by installing older `libstdcxx-ng`:
```
$ conda create -n cp python=3.8 contourpy libstdcxx-ng==11.2.0
$ conda activate cp
(cp) $ python -c 'import contourpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.conda/envs/cp/lib/python3.8/site-packages/contourpy/__init__.py", line 4, in <module>
    from ._contourpy import (
ImportError: /root/.conda/envs/cp/lib/python3.8/site-packages/contourpy/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/.conda/envs/cp/lib/python3.8/site-packages/contourpy/_contourpy.cpython-38-x86_64-linux-gnu.so)
```

So `contourpy` should either be built against the oldest possibly `libstdcxx-ng`, or should require a minimum version in the package metadata.

### Installed packages

```shell
# packages in environment at /root/.conda/envs/cp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
contourpy                 1.0.2            py38h43d8883_2    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libstdcxx-ng              11.2.0               h1234567_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.22.3           py38h99721a1_2    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
python                    3.8.13          ha86cf86_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                62.3.2           py38h578d9bd_0    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

### Environment info

```shell
active environment : cp
    active env location : /root/.conda/envs/cp
            shell level : 2
       user config file : /root/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /root/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.10.0.final.0
       virtual packages : __linux=5.17.7=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr  (read only)
      conda av data dir : /usr/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.10.0 Linux/5.17.7-200.fc35.x86_64 fedora/35 glibc/2.34
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by ianthomas23** [comment]
@QuLogic If I look at the metadata of the contourpy package that you installed:
```
$ conda search -i "contourpy[channel=conda-forge]==1.0.2" | grep "contourpy 1.0.2 py38h43d8883_2" -A 18
contourpy 1.0.2 py38h43d8883_2
------------------------------
file name   : contourpy-1.0.2-py38h43d8883_2.tar.bz2
name        : contourpy
version     : 1.0.2
build       : py38h43d8883_2
build number: 2
size        : 224 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/contourpy-1.0.2-py38h43d8883_2.tar.bz2
md5         : b28aa61bda641e608bf89518f60d015f
timestamp   : 2022-05-19 10:04:08 UTC
dependencies: 
  - libgcc-ng >=10.3.0
  - libstdcxx-ng >=10.3.0
  - numpy >=1.16
  - python >=3.8,<3.9.0a0
  - python_abi 3.8.* *_cp38
```
it shows that there is already a minimum version requirement on `libstdcxx-ng`. Your reproducer is using a later version than this minimum requirement, which should be fine but isn't, but this is a different problem. Or am I missing something here?

**Comment by ianthomas23** [comment]
Closing due to lack of response.
